DocName = "Algebra [1] - E.S. Golod"
RarName = "algebra-1s-golod"

all:
 cp index.ps $(DocName).ps
 cp index.pdf $(DocName).pdf
 wt $(RarName).rar $(DocName).ps
 wt $(RarName)-pdf.rar $(DocName).pdf
 

